name: codeclimat
  # run CodeClimat for project
on: [push]
jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10.7'
      - name: install dependecies
        run: |
          pip install poetry
          poetry install
      - name: Code Climate Coverage Action
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          CC_TEST_REPORTER_ID:  c919cf47b3f2cece149dcfec937dc9054be0986df71ab236c1d38d076788f330
        with:
          coverageCommand: make coverage-xml
          debug: true
