
name: tests
  # run tests for project
on: [push]
jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: install dependecies
        run: |
          pip install poetry
          poetry install
      - name: run tests
        run: |
          make test
